FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y

COPY ./scripts/entrypoint.db.sh .
COPY ./scripts/create-db.sql .

ENTRYPOINT [ "/bin/bash", "entrypoint.db.sh" ]
CMD [ "/opt/mssql/bin/sqlservr" ]